### ISSUE TITLE
Observations

### ISSUE THREAD

**Issue by FatimaPillosu** [esowc/ecPoint-PyCal#56]
Look at section "Observations" in the mock-up. Two parameters are requested:
1. The time when the observations start being collected (e.g. 2 UTC)
2. The discretization of the accumulation period's starting time (e.g. at 3-hourly intervals)
Therefore, the available observations will be at 2, 5, 8, 11, 14, 17, 20, 23 UTC.

Usually the parameters will be:
1. 0 UTC
2. 6
Therefore, the available observations will be at 0,6,12,18 UTC, but we want to consider all possibilities. For example, if a user has observations only for Australia, the user will be using the funny intervals in the first example.

**Comment by onyb** [comment]
Fixed in commit 7248219.

**Comment by onyb** [comment]
#### Screenshot

![discretization](https://user-images.githubusercontent.com/3684187/61335021-415aae00-a82c-11e9-9d1b-fc3090d45cb8.png)

#### Python code

https://github.com/esowc/ecPoint-PyCal/blob/7248219f474125de0666a1c4fc4c558c75827d19/core/processor/utils.py#L9-L13
