### ISSUE TITLE
Save and Visualisation of the point data table

### ISSUE THREAD

**Issue by FatimaPillosu** [esowc/ecPoint-PyCal#57]
- It is considered better to maintain the section "Output Point Data Table" to save the output file. This is because we experienced failures when the ascii table is visualised, and the software crashes. As the computations can take long time if long calibration periods are computed, it would be better to guarantee that the computations are saved immediately.

- Plus, having the "Output Point Data Table" section and the "save button" in the Processing tab seems to be redundant.

- When the file containing the point data table is visualised, the software can crash if the file is big. As visualising the files is interesting only for the first values, maybe it would be good to limit the visualisation of the point data table only to the first, let's say, 20 lines.

**Comment by onyb** [comment]
The following changes were done:
- Created a new section called "Output Data" with a subsection "Point data table".
  * The idea is to use this section for specifying the paths of other files to be saved, like the histograms.
  * Currently looks like this:
![output](https://user-images.githubusercontent.com/3684187/61329797-795af480-a81e-11e9-98e2-4d66b7fbf8bc.png)
- Removed the "Save ASCII Table" button in the Processing tab.
- Created #59 to track this separately.
