### ISSUE TITLE
Pre-computation of an accumulated predictand

### ISSUE THREAD

**Issue by FatimaPillosu** [esowc/ecPoint-PyCal#58]
If the variable used as predictand is accumulated, then the variable should be pre-computed, to not run the risk that the user forgets to computed to be able to select the minimum value chosen as threshold to avoid diving by zero. 
See mock-up for example.

**Comment by onyb** [comment]
Implemented in 05727a4.

![precomputations](https://user-images.githubusercontent.com/3684187/61910955-5d4e0600-af36-11e9-8e6b-df6903df926f.png)
